# .pages.yml
media:
  # Where Pages CMS will save uploaded images in your repo
  input: public/images
  # The path your Astro components will use to display those images
  output: /images

content:
  - name: products
    label: Shop Products
    type: collection
    # The folder where your Astro content collections live
    path: src/content/products
    # Naming convention for new product files
    filename: "{slug}.md"
    # The columns you see when looking at the list of products in Pages CMS
    view:
      fields: [title, sku, price, category]
    
    # Define the inputs the CMS user will see
    fields:
      - name: id
        label: Product ID
        type: string
        required: true
      - name: title
        label: Product Name
        type: string
        required: true
      - name: slug
        label: URL Slug (e.g., little-stars-pastina)
        type: string
        required: false
      - name: price
        label: Price
        type: number
        required: true
      - name: sku
        label: SKU (e.g., BABY-002)
        type: string
        required: false
      - name: age
        label: Recommended Age (e.g., 8+ Months)
        type: string
      - name: category
        label: Category
        type: select
        options: 
          - Pastas
          - Riso
          - Cereal
          - Biscuits
          - Puree
          - Yoghurt
          - Fruits
          - Meats
          - Cheese
          - Oil
          - Syrup
          - Lentils
          - Lotion
          - Body Wash
          - Other
        required: false
      - name: brand
        label: Brand
        type: string
        required: true
      - name: publish_date
        label: Publish Date
        type: date
        options:
          dateFormat: "MM-DD-YYYY"
      - name: image
        label: Product Image
        type: image
      - name: desc
        label: Product Description
        type: rich-text
      - name: body
        label: Product Details
        type: rich-text
    view:
      fields: [title, price, brand, publish_date]

settings:
  hide: true